/** Generated by YAKINDU Statechart Tools code generator. */
package fsmdrinkingfactory.drinkingfactory;

import fsmdrinkingfactory.IStatemachine;
import fsmdrinkingfactory.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IDrinkingFactoryStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseWelcome();
		
		public void raiseCancel();
		
		public void raiseSelectHotDrink();
		
		public void raiseSelectParam();
		
		public void raisePayCB();
		
		public void raiseAddCash();
		
		public void raiseValidate();
		
		public void raiseStartPrep();
		
		public void raiseStartServ();
		
		public void raiseDeliver();
		
		public void raiseAction();
		
		public void raiseFinishWash();
		
		public boolean isRaisedDoCancel();
		
		public boolean isRaisedDoWelcome();
		
		public boolean isRaisedDoHotDrink();
		
		public boolean isRaisedDoCB();
		
		public boolean isRaisedDoAddCash();
		
		public boolean isRaisedDoValid();
		
		public boolean isRaisedDoPrep();
		
		public boolean isRaisedDoServ();
		
		public boolean isRaisedDoWait();
		
		public boolean isRaisedDoWash();
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoCancelRaised();
		public void onDoWelcomeRaised();
		public void onDoHotDrinkRaised();
		public void onDoCBRaised();
		public void onDoAddCashRaised();
		public void onDoValidRaised();
		public void onDoPrepRaised();
		public void onDoServRaised();
		public void onDoWaitRaised();
		public void onDoWashRaised();
		}
	
	public SCInterface getSCInterface();
	
}
